### ISSUE TITLE
Friend Filter feature not working

### ISSUE THREAD

**Issue by blvcksvn** [Neraud/PADListener#81] opened 2015-04-15 06:55 UTC
HK version.
All friends are showing up to have either null images or evolutions of the starter dragons only.
Only rank and usernames and plus values are correct.
Leader History displays broken numbers such as 1747 Level, 93 Awakening, 99 Skill.

**Comment by Neraud** [comment] 2016-02-22 16:15
The issue was probably caused by the Best Friend flag.
Fixed by #99

**Closed by Neraud** 2016-02-22 16:15 UTC
Labels: bug
